import { categoryColors, currency, formatDate, type Expense } from "./expense-data";
import { categoryIcons, Icon } from "./dashboard-icon";

export function ExpensesTable({ expenses }: { expenses: Expense[] }) {
  return <section className="mt-6 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-[0_2px_10px_rgba(15,23,42,0.04)]">
    <div className="flex items-center justify-between border-b border-slate-200 px-5 py-5 sm:px-6"><div><h2 className="font-semibold text-[#142032]">Recent expenses</h2><p className="mt-1 text-sm text-slate-500">Your latest transactions</p></div><button type="button" className="text-sm font-semibold text-[#18845e] hover:text-[#126e4e]">View all</button></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-6 py-3 font-semibold">Expense</th><th className="px-6 py-3 font-semibold">Category</th><th className="px-6 py-3 font-semibold">Date</th><th className="px-6 py-3 text-right font-semibold">Amount</th></tr></thead><tbody className="divide-y divide-slate-100">{expenses.map((expense) => <tr key={expense.id} className="transition hover:bg-slate-50"><td className="px-6 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg text-white" style={{ backgroundColor: categoryColors[expense.category] ?? categoryColors.Other }}><Icon name={categoryIcons[expense.category] ?? "other"} className="h-[18px] w-[18px]" /></span><span className="font-medium text-[#263444]">{expense.title}</span></div></td><td className="px-6 py-4"><span className="rounded-md bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">{expense.category}</span></td><td className="px-6 py-4 text-slate-500">{formatDate(expense.date)}</td><td className="px-6 py-4 text-right font-semibold text-[#263444]">{currency.format(expense.amount)}</td></tr>)}</tbody></table></div>
  </section>;
}
